# Generated by Django 3.2.6 on 2021-08-21 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('isd', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISD')),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile No.')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='users/profile_pic')),
                ('short_intro', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('talent', models.CharField(blank=True, max_length=100, null=True)),
                ('interest', models.CharField(blank=True, max_length=100, null=True)),
                ('your_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('ios', 'Mobile/IOS'), ('android', 'Mobile/ANDROID'), ('web', 'WEB')], max_length=100, null=True)),
                ('login_type', models.CharField(blank=True, choices=[('native', 'Native'), ('google-oauth2', 'Google')], max_length=100, null=True)),
                ('user_type', models.CharField(blank=True, choices=[('customer', 'CUSTOMER')], max_length=100, null=True)),
                ('device_id', models.CharField(blank=True, max_length=225, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', db_column='city', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_userprofiles', show_all=True, to='configurations.citymaster')),
                ('country', models.ForeignKey(blank=True, db_column='country', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_userprofiles', to='configurations.countrymaster')),
                ('created_by', models.ForeignKey(db_column='created_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='created_userprofiles', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('state', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', db_column='state', limit_choices_to={'is_active': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_userprofiles', show_all=True, to='configurations.statemaster')),
                ('updated_by', models.ForeignKey(db_column='updated_by', limit_choices_to=models.Q(('is_staff', 0), ('is_superuser', 0), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_userprofiles', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveIntegerField()),
                ('otp_status', models.CharField(choices=[('delivered', 'Delivered'), ('not_delivered', 'Not Delivered'), ('successful', 'Successful'), ('expired', 'Expired')], max_length=20, verbose_name='OTP Status')),
                ('auth_type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email ID')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expired_datetime', models.DateTimeField(verbose_name='Expired At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two Factor Authentication',
                'verbose_name_plural': 'Two Factor Authentication',
                'db_table': 'two_factor_authentication',
                'ordering': ['-created_at'],
            },
        ),
    ]
