# Generated by Django 3.2.6 on 2021-08-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210828_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='random_password_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
