# Generated by Django 3.2.6 on 2021-09-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_random_password_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_source',
            field=models.CharField(choices=[('API', 'API'), ('TEMPLATE', 'TEMPLATE')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
