# Generated by Django 3.2.6 on 2021-08-21 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True)),
                ('payment_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '    Payment Type',
                'verbose_name_plural': '    Payment Type',
                'db_table': 'payment_type',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('payment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Payment Datetime')),
                ('invoice_amount', models.FloatField(verbose_name='Invoice Amount (in $)')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=100)),
                ('transaction_id', models.CharField(max_length=255, null=True, verbose_name='Payment Transaction ID')),
                ('chat_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction_chat_track', to='user_tracker.chattracking')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.currencymaster')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttype', verbose_name='Payment Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction_user', to=settings.AUTH_USER_MODEL)),
                ('video_call_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction_video_track', to='user_tracker.videotracking')),
            ],
            options={
                'verbose_name': 'User Payment Transaction',
                'verbose_name_plural': 'User Payment Transaction',
                'db_table': 'user_payment_type',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactionAfterCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Payment Datetime')),
                ('system_amount', models.FloatField(verbose_name='System Amount')),
                ('user_payble_amount', models.FloatField(verbose_name='User Payble Amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=100)),
                ('transaction_id', models.CharField(max_length=255, null=True, verbose_name='Payment Transaction ID')),
                ('payment_commission_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rule_instance', to='configurations.paymentcommissionrule')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttype', verbose_name='Payment Type')),
                ('system_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_currency_payment', to='configurations.currencymaster', verbose_name='System Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment_transaction_user', to=settings.AUTH_USER_MODEL)),
                ('user_payble_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_currency_payment', to='configurations.currencymaster', verbose_name='User Payble Currency')),
            ],
            options={
                'verbose_name': 'User Payment Transaction',
                'verbose_name_plural': 'User Payment Transaction',
                'db_table': 'payment_transaction_after_commission',
            },
        ),
    ]
