# Generated by Django 3.2.6 on 2021-08-21 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver_video_tracker', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender_video_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Tracking',
                'verbose_name_plural': 'Chat Tracking',
                'db_table': 'chat_tracking',
            },
        ),
        migrations.CreateModel(
            name='VideoTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Video Start Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Video End Time')),
                ('time_duration', models.CharField(blank=True, max_length=225, null=True, verbose_name='Time Duration')),
                ('video_call_status', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('is_active', 'Active'), ('decline', 'Decline')], max_length=100)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_receiver_video_tracker', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sender_video_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Tracking',
                'verbose_name_plural': 'Video Tracking',
                'db_table': 'video_tracking',
            },
        ),
        migrations.CreateModel(
            name='UserVideoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_history_user', to=settings.AUTH_USER_MODEL)),
                ('video_call_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tracking_history_instance', to='user_tracker.videotracking')),
            ],
            options={
                'verbose_name': 'User Video History',
                'verbose_name_plural': 'User Video History',
                'db_table': 'user_video_history',
            },
        ),
        migrations.CreateModel(
            name='UserEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('chat_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_tracking_instance', to='user_tracker.chattracking')),
                ('earn_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earn_user', to=settings.AUTH_USER_MODEL)),
                ('spent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spent_user', to=settings.AUTH_USER_MODEL)),
                ('video_call_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_earn_video_tracking_instance', to='user_tracker.videotracking')),
            ],
            options={
                'verbose_name': 'Earning User',
                'verbose_name_plural': 'Earning User',
                'db_table': 'earning_user',
            },
        ),
        migrations.CreateModel(
            name='DeactivateUserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deactivate User Count',
                'verbose_name_plural': 'Deactivate User Count',
                'db_table': 'deactivate_user_count',
            },
        ),
        migrations.CreateModel(
            name='BlockTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_block_status', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_receiver_video_tracker', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_sender_video_tracker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Block Tracking',
                'verbose_name_plural': 'Block Tracking',
                'db_table': 'block_tracking',
            },
        ),
    ]
