# Generated by Django 3.2.6 on 2021-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blocktracking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
